/*
'''
LeetCode 389:Find the Difference
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
 */


package pers.you.learning.leetcode.seventeentwo;

import java.util.Arrays;

public class FindTheDifference {

    public char findTheDifferenceV1(String s, String t) {
		boolean ok=true;
		char[] charS = s.toCharArray();
		char[] charT = t.toCharArray();
		Arrays.sort(charS);
		Arrays.sort(charT);
		for(int i=0;i<charT.length-1;i++){
			if(charT[i]!=charS[i]){
			    return charT[i];
			}
		}
		return charT[charT.length-1];
	}
    
    public char findTheDifferenceV2(String s, String t) {
        char ans = 0;
        for(int i=0;i<s.length();i++){
            ans^=s.charAt(i);
        }
        for(int j=0;j<t.length();j++){
            ans^=t.charAt(j);
        }
        return ans;
}
}
